package com.caogen.jfd.websocket;

import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;

public class MyClientApp {

    public static void main(String[] args){
        // TODO todo.generated by zoer
        Timer timer = new Timer();
        timer.schedule(new MyTask(), 1000, 2000);
    }
    static int num = 0;
    static class MyTask extends TimerTask {

        @Override
        public void run() {
            MyClient client = new MyClient();
            String uri = "ws://localhost:8080/MyWebSocket/websocket?service123";
            client.start(uri);
            try {
                num++;
                client.sendMessage("消息测试"+num);
                client.closeSocket();
                System.out.println(num);
            } catch (IOException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        }

    }

}
